name: Build & Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker Image
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get git hash
        run: echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}
          build-args: |
            GIT_HASH=${{ env.GIT_HASH }}
            DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }}

      # Deploy to CapRover
      - name: Deploy Image to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ vars.CAPROVER_SERVER }}"
          app: "${{ vars.APP_NAME }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}

      - name: send telegram message
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ‚úÖ *A build/deploy job finished*
            ‚ñ∂Ô∏è *Status: ${{ job.status }}*
            #Ô∏è‚É£ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            ü§° Developer: *${{github.actor}}*
            üí¨ Commit message: ${{ github.event.commits[0].message }}
            üîó Href: https://github.com/${{github.repository}}

            ‚ú® See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          format: markdown
          disable_web_page_preview: "True"
